# Generated by Django 5.1.4 on 2025-01-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
    ]
