# Generated by Django 5.1.4 on 2025-01-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recipeingredient_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
